#!/bin/bash

# If the virtual environment doesn't already exist, build it and install
# the necessary packages. This assumes python, pip, numpy, and fisher are
# already available.
if [[ ! -d env ]]; then
    virtualenv env
    . env/bin/activate
    pip install ../../python/SRL/dist/*.tar.gz
    pip install ../python-eventdetector-service/package/dist/*.tar.gz
else
    . env/bin/activate
fi

export PORT=`docker inspect autonlab-tad | grep -n HostPort | awk '{print $3}' | sed 's/\"//g'`
if [[ ! -n "$PORT" ]]; then
    echo "No port detected. The default 12345 will be used. (This will only work if the server is running on the host.)"
fi
python client.py $PORT
