#!/bin/bash

set -x
export PORT=`docker inspect autonlab-tad | grep -n HostPort | awk '{print $3}' | sed 's/\"//g'`
if [[ ! -n "$PORT" ]]; then
    echo "No port detected. The default 5200 will be used. (This will only work if the server is running on the host.)"
    export PORT=5200
fi
tok_id=`curl -XPOST localhost:$PORT/event-report -d "target-location=Colorado Springs;Colorado;United States" -d "baseline-location=;Colorado;United States" -d "analysis-start-date=2014/01/05" -d "analysis-end-date=2014/02/05" -d "stratify=false" | sed 's/{"task-id": "//' | sed 's/"}//'`
watch -n 3 curl localhost:$PORT/event-report/$tok_id
set +x
