#!/bin/bash

set -x
export PORT=`docker inspect autonlab-tad | grep -n HostPort | awk '{print $3}' | sed 's/\"//g'`
if [[ ! -n "$PORT" ]]; then
    echo "No port detected. The default 5000 will be used. (This will only work if the server is running on the host.)"
    export PORT=5000
fi
tok_id=`curl localhost:$PORT/event-report -X POST -H "Content-Type: application/json" -d '{"target-filters":{"city": "Colorado Springs", "state": "Colorado"}, "baseline-filters": {"state": "Colorado"}, "analysis-start-date": "2014/01/05", "analysis-end-date": "2014/02/05"}' | sed 's/{"task-id": "//' | sed 's/"}//'`
echo "Token: $tok_id"
watch -n 3 curl localhost:$PORT/event-report/$tok_id
set +x
