#!/bin/bash

sleep 5
cd /service
log='logs/tad.log'

if [ -d "logs" ]; then
    if [ -f "$log" ]; then
        echo "" &>> $log
    fi
else
    log='/dev/stdout'
fi

echo `date` &>> $log
python ./tad/tad.py &>> $log &
