#!/bin/bash

entrypoint=""
mounts=""

if [[ $# -eq 1 ]] && [[ "$1" == "-h" ]]; then
    echo "Usage:                                                Entrypoint:"
    echo "  run-docker                                          /service/run"
    echo "  run-docker <entry_point>                            <entry_point>"
    exit
fi

if [[ $# -gt 1 ]]; then
    echo "Too many parameters."
else
    if [[ $# -eq 1 ]]; then
        entrypoint="--entrypoint $1"
    fi

    docker run -ti --rm --name "autonlab-tad" $entrypoint -P autonlab/tad
fi
