#!/bin/bash

entrypoint=""
mounts=""

if [[ $# -eq 1 && "$1" -eq "-h" ]]; then
    echo "Usage:                                                Entrypoint:"
    echo "  run-docker                                          /bin/bash"
    echo "  run-docker <entry_point>                            <entry_point>"
    echo "  run-docker <log_dir> <data_dir>                     /service/run"
    echo "  run-docker <log_dir> <data_dir> <entry_point>       <entry_point>"
    exit
fi

if [[ $# -gt 3 ]]; then
    echo "Too many parameters."
else
    if [[ $# -eq 0 ]]; then
        entrypoint="--entrypoint bash"
    elif [[ $# -eq 1 ]]; then
        entrypoint="--entrypoint $1"
    elif [[ $# -eq 3 ]]; then
        entrypoint="--entrypoint $3"
    fi

    if [[ $# -gt 1 ]]; then
        mounts="-v `readlink -f $1`:/service/logs -v `readlink -f $2`:/service/snapshot:ro"
    fi

    docker run -ti --rm --name "eventdetector" $mounts $entrypoint -P eventdetector
fi
